/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ServicosDAO;
import funcoes.Telas;
import funcoes.Validacoes;
import javax.swing.JOptionPane;
import model.Servico;

/**
 *
 * @author maikon.rosa
 */
public class JF_Haras extends javax.swing.JFrame {
Telas telas = new Telas();
Validacoes campo = new Validacoes();     
    ServicosDAO servicoDao = new ServicosDAO();
    Servico servico = new Servico();
/**
     * Creates new form JF_Celeiro
     */
    public JF_Haras() {
        initComponents();
         telas.Resolucao(this);
         servicoDao.CarregarTabelaServ(tab_serv, pesquisa);
         servicoDao.CarregarBaias(1, tab_baias);
         servicoDao.carregarNbaias(b_d, b_u,b_da);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baias_tab = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_animais = new javax.swing.JButton();
        btn_celeiro = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        btn_calendario = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        home = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        b_d = new javax.swing.JTextField();
        b_da = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_baias = new javax.swing.JTable();
        b_todas = new javax.swing.JCheckBox();
        b_dispo = new javax.swing.JCheckBox();
        b_uso = new javax.swing.JCheckBox();
        b_dani = new javax.swing.JCheckBox();
        b_u = new javax.swing.JTextField();
        ad_baia = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cat_cat = new javax.swing.JComboBox<>();
        Categoria = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        cat_nome = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        cat_valor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_serv = new javax.swing.JTable();
        cadastra = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        atualiza = new javax.swing.JButton();
        nomeerro = new javax.swing.JLabel();
        caterro = new javax.swing.JLabel();
        valorerro = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ch_nome = new javax.swing.JCheckBox();
        ch_cat = new javax.swing.JCheckBox();
        ch_valor = new javax.swing.JCheckBox();
        btn_home = new javax.swing.JButton();
        jdata = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jnome = new javax.swing.JTextField();
        btn_animais1 = new javax.swing.JButton();
        btn_rh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_usuario1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        btn_animais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cavalo.png"))); // NOI18N
        btn_animais.setText("Animais       ");
        btn_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animaisActionPerformed(evt);
            }
        });

        btn_celeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_celeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celeiro.png"))); // NOI18N
        btn_celeiro.setText("Haras");
        btn_celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_celeiroActionPerformed(evt);
            }
        });

        btn_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_usuario.setText(" Usuários ");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        btn_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendario.png"))); // NOI18N
        btn_calendario.setText("Calendário");
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log.png"))); // NOI18N
        btn_log.setText("Log          ");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        home.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 153, 153)));
        home.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homeComponentShown(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Baias ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 0, 14))); // NOI18N

        b_d.setEditable(false);
        b_d.setBackground(new java.awt.Color(255, 255, 255));
        b_d.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        b_d.setForeground(new java.awt.Color(0, 204, 51));
        b_d.setBorder(javax.swing.BorderFactory.createTitledBorder("Disponiveis"));
        b_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dActionPerformed(evt);
            }
        });

        b_da.setEditable(false);
        b_da.setBackground(new java.awt.Color(255, 255, 255));
        b_da.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        b_da.setForeground(new java.awt.Color(255, 51, 0));
        b_da.setBorder(javax.swing.BorderFactory.createTitledBorder("Danificada"));

        tab_baias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_baias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_baiasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_baias);

        b_todas.setText("Todas");
        b_todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_daniActionPerformed(evt);
            }
        });

        b_dispo.setText("Disponiveis");
        b_dispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_daniActionPerformed(evt);
            }
        });

        b_uso.setText("Em uso");
        b_uso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_daniActionPerformed(evt);
            }
        });

        b_dani.setText("Danificadas");
        b_dani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_daniActionPerformed(evt);
            }
        });

        b_u.setEditable(false);
        b_u.setBackground(new java.awt.Color(255, 255, 255));
        b_u.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        b_u.setBorder(javax.swing.BorderFactory.createTitledBorder("Em uso"));

        ad_baia.setText("Nova");
        ad_baia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_baiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(b_d, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(b_u, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_da, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ad_baia))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(b_todas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_dispo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_uso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_dani)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ad_baia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_todas)
                    .addComponent(b_dispo)
                    .addComponent(b_uso)
                    .addComponent(b_dani))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serviços", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 0, 11))); // NOI18N

        cat_cat.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        cat_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alojamento ", "Treinamento", "Cuidados", "Outros", " " }));

        Categoria.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        Categoria.setText("Categoria ");

        nome.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        nome.setText("Nome :");

        cat_nome.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        valor.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        valor.setText("Valor ");

        cat_valor.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        cat_valor.setText("R$ 0,00");
        cat_valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cat_valorFocusGained(evt);
            }
        });
        cat_valor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cat_valorMouseClicked(evt);
            }
        });
        cat_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cat_valorKeyReleased(evt);
            }
        });

        tab_serv.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tab_serv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_serv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_servMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_serv);

        cadastra.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        cadastra.setText("Cadastrar");
        cadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        cancelar.setText("Cancelar ");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        atualiza.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        atualiza.setText("Atualizar ");
        atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaActionPerformed(evt);
            }
        });

        nomeerro.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        caterro.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        valorerro.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        pesquisa.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel7.setText("Pesquisar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cat_valor)
                            .addComponent(cadastra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(atualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomeerro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorerro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cat_nome)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cat_cat, 0, 221, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(ch_valor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ch_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)
                                .addComponent(caterro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ch_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Categoria)
                            .addComponent(ch_cat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cat_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(caterro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(ch_nome)
                            .addComponent(nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cat_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeerro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valor)
                            .addComponent(ch_valor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cat_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorerro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(cadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualiza)
                            .addComponent(cancelar))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        cancelar.setVisible(false);
        atualiza.setVisible(false);
        ch_nome.setVisible(false);
        ch_cat.setVisible(false);
        ch_valor.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        home.addTab("Celeiro", jPanel2);

        btn_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel84.setText("Seja Bem-Vindo");

        btn_animais1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_animais1.setText("Cliente        ");
        btn_animais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animais1ActionPerformed(evt);
            }
        });

        btn_rh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_rh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manutencao.png"))); // NOI18N
        btn_rh.setText("R. H.         ");
        btn_rh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rhActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_usuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/service.png"))); // NOI18N
        btn_usuario1.setText("Serviços");
        btn_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel84)
                        .addGap(62, 62, 62))
                    .addComponent(btn_animais1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_celeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btn_rh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_animais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btn_animais)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_animais1)
                                .addGap(5, 5, 5)
                                .addComponent(btn_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_celeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_rh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_log)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_usuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_home)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_usuario1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_animaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animaisActionPerformed
 telas.alterar(this, 5);    
    }//GEN-LAST:event_btn_animaisActionPerformed

    private void btn_celeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_celeiroActionPerformed
 telas.alterar(this, 7);
    }//GEN-LAST:event_btn_celeiroActionPerformed

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
telas.alterar(this, 12);
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calendarioActionPerformed
telas.alterar(this, 4);        
    }//GEN-LAST:event_btn_calendarioActionPerformed

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
 telas.alterar(this, 13);
    }//GEN-LAST:event_btn_logActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
telas.alterar(this,1);                              
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_animais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animais1ActionPerformed
 telas.alterar(this, 2);
    }//GEN-LAST:event_btn_animais1ActionPerformed

    private void btn_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario1ActionPerformed
 telas.alterar(this, 3);                     
    }//GEN-LAST:event_btn_usuario1ActionPerformed

    private void homeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homeComponentShown

    }//GEN-LAST:event_homeComponentShown

    private void btn_rhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rhActionPerformed
 telas.alterar(this, 11); 
    }//GEN-LAST:event_btn_rhActionPerformed

    private void b_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_dActionPerformed

    private void cadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraActionPerformed
     if(campo.Campoescolha(cat_cat, caterro)){
                        servico.setServico_cat(String.valueOf(cat_cat.getSelectedItem()));
         if(campo.CampoTexto(cat_nome, nomeerro)){
                        servico.setServico_nome(cat_nome.getText());
                        if(campo.Camponumero(cat_valor, valorerro)){
                         servico.setServico_preco(Float.parseFloat(cat_valor.getText()));
                        servicoDao.adicionarServicos(servico);
                        servicoDao.CarregarTabelaServ(tab_serv, pesquisa);
                        }
            }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_cadastraActionPerformed

    private void cat_valorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_valorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_valorMouseClicked

    private void cat_valorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cat_valorFocusGained
        cat_valor.setText("");
            
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_valorFocusGained

    private void cat_valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cat_valorKeyReleased
        String valor ="";
        for(int i =0;i<cat_valor.getText().length();i++){
            char s= cat_valor.getText().charAt(i);
            if(s==',')
                valor=valor+".";
            else 
                valor=valor+s;
        
            
        }
        cat_valor.setText(valor);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_valorKeyReleased

    private void tab_servMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_servMouseClicked
            int linha = tab_serv.getSelectedRow();
            String id = String.valueOf(tab_serv.getValueAt(linha, 0));
            int ID = Integer.parseInt(id);
            servico.setServico_id(ID);
            String cat = String.valueOf(tab_serv.getValueAt(linha, 1));
            String nom = String.valueOf(tab_serv.getValueAt(linha, 2));
            String preco = String.valueOf(tab_serv.getValueAt(linha, 3));
              String opcoes[] = {"Alterar","Deletar","Cancelar"};
             int opc = JOptionPane.showOptionDialog(null, "Selecione o que deseja fazer com o servico", "Confiraçao"
            , JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[2]);
             switch(opc ){
            case 0:telas.alterarTelaservco( nome, Categoria, valor, ch_nome, ch_cat, ch_valor, cadastra, atualiza, cancelar);
            cat_cat.setSelectedItem(cat);
            cat_nome.setText(nom);
            cat_valor.setText(preco);
            break;
            case 1:servicoDao.apagarervico(servico);servicoDao.CarregarTabelaServ(tab_serv, pesquisa);break;
            default:;
             } 

        // TODO add your handling code here:
    }//GEN-LAST:event_tab_servMouseClicked

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
            telas.alterarTelaservco( nome, Categoria, valor, ch_nome, ch_cat, ch_valor, cadastra, atualiza, cancelar);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaActionPerformed
            if(ch_cat.isSelected()){
                if(campo.Campoescolha(cat_cat, caterro)){
                  servico.setServico_cat(String.valueOf(cat_cat.getSelectedItem()));
                  servicoDao.alterarServ(servico, 1);
                }
            }
            if(ch_nome.isSelected()){
                if(campo.CampoTexto(cat_nome, nomeerro)){
                    servico.setServico_nome(cat_nome.getText());
                servicoDao.alterarServ(servico, 2);}
            }
            if(ch_valor.isSelected()){
                if(campo.Camponumero(cat_valor, valorerro)){
                    servico.setServico_preco(Float.parseFloat(cat_valor.getText()));
                     servicoDao.alterarServ(servico, 3);}
            }
        servicoDao.CarregarTabelaServ(tab_serv, pesquisa);
        telas.alterarTelaservco( nome, Categoria, valor, ch_nome, ch_cat, ch_valor, cadastra, atualiza, cancelar);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizaActionPerformed

    private void b_daniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_daniActionPerformed
        //1
        if( b_dani.isSelected()&&b_dispo.isSelected()&&b_uso.isSelected()){
            b_dani.setSelected(false);
            b_uso.setSelected(false);
            b_dispo.setSelected(false);
            b_todas.setSelected(true);
            servicoDao.CarregarBaias(1, tab_baias);
        //2    
       }else if(b_dani.isSelected()&&b_dispo.isSelected()){
            b_todas.setSelected(false);
            servicoDao.CarregarBaias(2, tab_baias);
        //3    
       }else if(b_dani.isSelected()&&b_uso.isSelected()){
            b_todas.setSelected(false);
            servicoDao.CarregarBaias(3, tab_baias);
        //4    
       }else if(b_dispo.isSelected()&&b_uso.isSelected()){
            b_todas.setSelected(false);
            servicoDao.CarregarBaias(4, tab_baias);
            //5
       }else if(b_dani.isSelected()&&b_uso.isSelected()){
             b_todas.setSelected(false);
             servicoDao.CarregarBaias(5, tab_baias);
            //6
       }else if(b_dani.isSelected()&&b_dispo.isSelected()==false&&b_uso.isSelected()==false){
            b_todas.setSelected(false);
              servicoDao.CarregarBaias(6, tab_baias);
            //7
       }else if(b_dani.isSelected()==false&&b_dispo.isSelected()&&b_uso.isSelected()==false){
            b_todas.setSelected(false);
              servicoDao.CarregarBaias(7, tab_baias);
            //8
       }else if(b_dani.isSelected()==false&&b_dispo.isSelected()==false&&b_uso.isSelected()){
            b_todas.setSelected(false);
              servicoDao.CarregarBaias(8, tab_baias);
       }else{
           servicoDao.CarregarBaias(1, tab_baias);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_b_daniActionPerformed

    private void ad_baiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_baiaActionPerformed
            servicoDao.Inserirbaia();
            servicoDao.CarregarBaias(1, tab_baias);
           servicoDao.carregarNbaias(b_d, b_u,b_da);
        // TODO add your handling code here:
    }//GEN-LAST:event_ad_baiaActionPerformed

    private void tab_baiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_baiasMouseClicked
           int opc;
        int linha = tab_baias.getSelectedRow();
            String loc = String.valueOf(tab_baias.getValueAt(linha, 0));
            String Status = String.valueOf(tab_baias.getValueAt(linha, 1));
            int local = Integer.parseInt(loc);
            switch(Status){
                case "Disponivel":String opcoes[] = {"Danificada","Cancelar"};
             opc = JOptionPane.showOptionDialog(null, "Selecionar o estado da Baia", "Modificar Baia"
            , JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
             if(opc==0){
              servicoDao.Alterarbaia(local, 1);
              servicoDao.CarregarBaias(1, tab_baias);
              servicoDao.carregarNbaias(b_d, b_u,b_da);
             }
             
             break;
                case "Danificada": String opcoes2[] = {"Disponível","Cancelar"};
             opc = JOptionPane.showOptionDialog(null, "Selecionar o estado da Baia", "Modificar Baia"
            , JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes2, opcoes2[1]);
              if(opc==0){
              servicoDao.Alterarbaia(local, 2);
              servicoDao.CarregarBaias(1, tab_baias);
              servicoDao.carregarNbaias(b_d, b_u,b_da);
             }
             break;
                default: JOptionPane.showMessageDialog(null,"Está baia está em uso" );
            }
         servicoDao.carregarNbaias(b_d, b_u,b_da);
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_baiasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Haras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Haras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Haras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Haras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Haras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categoria;
    private javax.swing.JButton ad_baia;
    private javax.swing.JButton atualiza;
    private javax.swing.JTextField b_d;
    private javax.swing.JTextField b_da;
    private javax.swing.JCheckBox b_dani;
    private javax.swing.JCheckBox b_dispo;
    private javax.swing.JCheckBox b_todas;
    private javax.swing.JTextField b_u;
    private javax.swing.JCheckBox b_uso;
    private javax.swing.ButtonGroup baias_tab;
    private javax.swing.JButton btn_animais;
    private javax.swing.JButton btn_animais1;
    private javax.swing.JButton btn_calendario;
    private javax.swing.JButton btn_celeiro;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_rh;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton btn_usuario1;
    private javax.swing.JButton cadastra;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> cat_cat;
    private javax.swing.JTextField cat_nome;
    private javax.swing.JTextField cat_valor;
    private javax.swing.JLabel caterro;
    private javax.swing.JCheckBox ch_cat;
    private javax.swing.JCheckBox ch_nome;
    private javax.swing.JCheckBox ch_valor;
    private javax.swing.JTabbedPane home;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JLabel jdata;
    private javax.swing.JTextField jnome;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nomeerro;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JTable tab_baias;
    private javax.swing.JTable tab_serv;
    private javax.swing.JLabel valor;
    private javax.swing.JLabel valorerro;
    // End of variables declaration//GEN-END:variables
}
