/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CargoDAO;
import controller.UsuarioDAO;
import controller.ValidacoesDao;
import funcoes.F_JF_principal;
import funcoes.F_atualizar_usuario;
import funcoes.Telas;
import funcoes.Validacoes;
import javax.swing.JOptionPane;
import model.Misc;
import model.Usuario;

/**
 *
 * @author maikon.rosa
 */
public class JF_Ususario extends javax.swing.JFrame {
   UsuarioDAO usu = new UsuarioDAO();
    Usuario usuario = new Usuario();
     Telas telas = new Telas();
     Validacoes campo = new Validacoes();
    /**
     * Creates new form JF_Ususario
     */
    public JF_Ususario() {
        initComponents();
        telas.Resolucao(this);
       usu.carregaTabela(1, tab_usu, usu_pesq);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_animais = new javax.swing.JButton();
        btn_celeiro = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        btn_calendario = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        home = new javax.swing.JTabbedPane();
        at_usuario5 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        usu_pesq = new javax.swing.JTextField();
        jScrollPane27 = new javax.swing.JScrollPane();
        tab_usu = new javax.swing.JTable();
        jLabel125 = new javax.swing.JLabel();
        usu_nome = new javax.swing.JTextField();
        loginerro = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        usu_login = new javax.swing.JTextField();
        senhaerro = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        usu_status = new javax.swing.JComboBox<>();
        cad_usu = new javax.swing.JButton();
        jLabel153 = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        usu_senha = new javax.swing.JTextField();
        jLabel155 = new javax.swing.JLabel();
        conf_senha = new javax.swing.JTextField();
        confsenhaerro = new javax.swing.JLabel();
        ch_usucad5 = new javax.swing.JCheckBox();
        ch_usuNcad5 = new javax.swing.JCheckBox();
        alterar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        ch_login = new javax.swing.JCheckBox();
        ch_senha = new javax.swing.JCheckBox();
        ch_status = new javax.swing.JCheckBox();
        btn_home = new javax.swing.JButton();
        jdata = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jnome = new javax.swing.JTextField();
        btn_rh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_usuario1 = new javax.swing.JButton();
        btn_animais1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        btn_animais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cavalo.png"))); // NOI18N
        btn_animais.setText("Animais       ");
        btn_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animaisActionPerformed(evt);
            }
        });

        btn_celeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_celeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celeiro.png"))); // NOI18N
        btn_celeiro.setText("Haras");
        btn_celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_celeiroActionPerformed(evt);
            }
        });

        btn_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_usuario.setText(" Usuários ");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        btn_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendario.png"))); // NOI18N
        btn_calendario.setText("Calendário");
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log.png"))); // NOI18N
        btn_log.setText("Log          ");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        home.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(153, 153, 153)));
        home.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homeComponentShown(evt);
            }
        });

        at_usuario5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                at_usuario5at_usuario1ComponentShown(evt);
            }
        });

        jLabel107.setText("Pesquisar ");

        usu_pesq.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        usu_pesq.setToolTipText("");
        usu_pesq.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));
        usu_pesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usu_pesqusu_pesq1KeyReleased(evt);
            }
        });

        tab_usu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        tab_usu.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        tab_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Login ", "Email", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_usuat_usu_tab1MouseClicked(evt);
            }
        });
        jScrollPane27.setViewportView(tab_usu);

        jLabel125.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel125.setText("Nome :");

        usu_nome.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        usu_nome.setToolTipText("");
        usu_nome.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));

        loginerro.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        loginerro.setForeground(new java.awt.Color(255, 0, 0));

        lbl_login.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lbl_login.setText("Login :");

        usu_login.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        usu_login.setToolTipText("");
        usu_login.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));

        senhaerro.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        senhaerro.setForeground(new java.awt.Color(255, 0, 0));

        lbl_status.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lbl_status.setText("Status :");

        usu_status.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        usu_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desativado","Ativo" }));
        usu_status.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));
        usu_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usu_statusat_usu_status1ActionPerformed(evt);
            }
        });

        cad_usu.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        cad_usu.setText("Cadastrar ");
        cad_usu.setEnabled(false);
        cad_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_usuat_usu_btn1ActionPerformed(evt);
            }
        });

        jLabel153.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel153.setText("Gerenciar Usuários");

        lbl_senha.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lbl_senha.setText("Senha");

        usu_senha.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        usu_senha.setToolTipText("");
        usu_senha.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));

        jLabel155.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel155.setText("Confirma senha");

        conf_senha.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        conf_senha.setToolTipText("");
        conf_senha.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));

        confsenhaerro.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        confsenhaerro.setForeground(new java.awt.Color(255, 0, 0));

        ch_usucad5.setText("Funcionario com usuarios ");
        ch_usucad5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ch_usucad5MouseClicked(evt);
            }
        });

        ch_usuNcad5.setText("Funcionario sem usuario ");
        ch_usuNcad5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ch_usucad5MouseClicked(evt);
            }
        });

        alterar.setText("Alterar ");
        alterar.setVisible(false);
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setVisible(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ch_login.setVisible(false);

        ch_senha.setVisible(false);

        ch_status.setVisible(false);

        javax.swing.GroupLayout at_usuario5Layout = new javax.swing.GroupLayout(at_usuario5);
        at_usuario5.setLayout(at_usuario5Layout);
        at_usuario5Layout.setHorizontalGroup(
            at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(at_usuario5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usu_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cad_usu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(at_usuario5Layout.createSequentialGroup()
                        .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel155)
                            .addComponent(jLabel125)
                            .addGroup(at_usuario5Layout.createSequentialGroup()
                                .addComponent(lbl_login)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_login))
                            .addGroup(at_usuario5Layout.createSequentialGroup()
                                .addComponent(lbl_status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_status))
                            .addComponent(usu_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usu_login, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usu_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(at_usuario5Layout.createSequentialGroup()
                                .addComponent(lbl_senha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_senha))
                            .addComponent(conf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confsenhaerro, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaerro, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginerro, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel153)
                            .addGroup(at_usuario5Layout.createSequentialGroup()
                                .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(at_usuario5Layout.createSequentialGroup()
                        .addComponent(jLabel107)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usu_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ch_usucad5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ch_usuNcad5))
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        at_usuario5Layout.setVerticalGroup(
            at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(at_usuario5Layout.createSequentialGroup()
                .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(at_usuario5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel153)
                            .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel107)
                                .addComponent(usu_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ch_usucad5)
                                .addComponent(ch_usuNcad5)))
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(at_usuario5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel125)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usu_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ch_login)
                            .addComponent(lbl_login))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usu_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginerro, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_senha)
                            .addComponent(ch_senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, at_usuario5Layout.createSequentialGroup()
                                .addComponent(usu_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(senhaerro, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel155)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confsenhaerro, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_status))
                            .addComponent(ch_status, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usu_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cad_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(at_usuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alterar)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        home.addTab("Usuario", at_usuario5);

        btn_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel84.setText("Seja Bem-Vindo");

        btn_rh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_rh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manutencao.png"))); // NOI18N
        btn_rh.setText("R. H.         ");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_usuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/service.png"))); // NOI18N
        btn_usuario1.setText("Serviços");
        btn_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario1ActionPerformed(evt);
            }
        });

        btn_animais1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_animais1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario.png"))); // NOI18N
        btn_animais1.setText("Cliente        ");
        btn_animais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animais1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel84)
                        .addGap(62, 62, 62))
                    .addComponent(btn_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_celeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_rh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_animais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_animais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btn_animais)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_animais1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_celeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_rh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_log)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_usuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_home)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_usuario1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jdata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        telas.alterar(this,1);
    }                                        
    private void btn_animais1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
         telas.alterar(this, 2);
    }   
    
    private void btn_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        telas.alterar(this, 3);        
    }    
    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {                                               
       telas.alterar(this, 4);
    }         
    private void btn_animaisActionPerformed(java.awt.event.ActionEvent evt) {                                            
       telas.alterar(this, 5);
    }                  
 private void btn_pastagemActionPerformed(java.awt.event.ActionEvent evt) {                                             
      telas.alterar(this, 6);
    }                                            
    private void btn_celeiroActionPerformed(java.awt.event.ActionEvent evt) {                                            
      telas.alterar(this, 7);
    }                                           
   private void btn_ferrajamentoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       telas.alterar(this, 8);
    }                                                
private void btn_veterinarioActionPerformed(java.awt.event.ActionEvent evt) {                                                
     telas.alterar(this, 9);
    }                                               

    private void btn_financeiroActionPerformed(java.awt.event.ActionEvent evt) {                                               
        telas.alterar(this, 10);
    }    
       private void btn_rhActionPerformed(java.awt.event.ActionEvent evt) {                                       
       telas.alterar(this, 11);
        
    }        
  private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
    telas.alterar(this, 12);
    }                                           
    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {                                        
 telas.alterar(this, 13);
    }                                       

  
    private void homeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homeComponentShown

        // TODO add your handling code here:
    }//GEN-LAST:event_homeComponentShown

    private void usu_pesqusu_pesq1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usu_pesqusu_pesq1KeyReleased
           if(ch_usuNcad5.isSelected() && ch_usucad5.isSelected())
               usu.carregaTabela(1, tab_usu, usu_pesq);
           else if( ch_usucad5.isSelected())
               usu.carregaTabela(2, tab_usu, usu_pesq);
           else if( ch_usuNcad5.isSelected())
                usu.carregaTabela(3, tab_usu, usu_pesq);
           else
               usu.carregaTabela(1, tab_usu, usu_pesq);
        // TODO add your handling code here:
    }//GEN-LAST:event_usu_pesqusu_pesq1KeyReleased
boolean alterado=false;
    private void tab_usuat_usu_tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_usuat_usu_tab1MouseClicked
           int linha = tab_usu.getSelectedRow();
            String nome = String.valueOf(tab_usu.getValueAt(linha, 1));
            String id =  String.valueOf(tab_usu.getValueAt(linha, 0));
            String login = String.valueOf(tab_usu.getValueAt(linha, 2));
            if(login.equals("Sem Usuario")){
                if(alterado){  
                 telas.alterartelaUsuario(lbl_login, lbl_senha, lbl_status, ch_login, ch_senha, ch_status, cad_usu, alterar, cancelar);
                alterado=false;}
                cad_usu.setEnabled(true);
                  usu_nome.setText(nome);
                  usuario.setPessoa_pessoa_id(Integer.parseInt(id));
            }else{
           String opcoes[] = {"Alterar","Deletar","Cancelar"};
             int opc = JOptionPane.showOptionDialog(null, "Oque deseja "+nome+"", "Confiraçao"
            , JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[2]);
             switch(opc ){
            case 0:
            telas.alterartelaUsuario(lbl_login, lbl_senha, lbl_status, ch_login, ch_senha, ch_status, cad_usu, alterar, cancelar);
            usuario.setPessoa_pessoa_id(Integer.parseInt(id));
            usu_nome.setText(nome);
            alterado=true;
            ;break;//Alterar
            case 1: usuario.setPessoa_pessoa_id(Integer.parseInt(id));usu.deletarUsu(usuario);usu.carregaTabela(1, tab_usu, usu_pesq);break;//Deleta
            default:
        }
            }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_usuat_usu_tab1MouseClicked

    private void usu_statusat_usu_status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usu_statusat_usu_status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usu_statusat_usu_status1ActionPerformed

    private void cad_usuat_usu_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_usuat_usu_btn1ActionPerformed
             if(campo.CampoTexto(usu_login, loginerro)){//começo Login
                 usuario.setUsuario_login(usu_login.getText());
            if(campo.Camposenha(usu_senha, conf_senha, senhaerro)){
                usuario.setUsuario_senha(usu_senha.getText());
                usuario.setUsuario_status(usu_status.getSelectedIndex());
                usu.cadUsuario(usuario);
                usu.carregaTabela(1, tab_usu, usu_pesq);
            }//senha
        }//fim nome
        // TODO add your handling code here:
    }//GEN-LAST:event_cad_usuat_usu_btn1ActionPerformed

    private void at_usuario5at_usuario1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_at_usuario5at_usuario1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_at_usuario5at_usuario1ComponentShown

    private void ch_usucad5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ch_usucad5MouseClicked
           if(ch_usuNcad5.isSelected() && ch_usucad5.isSelected())
               usu.carregaTabela(1, tab_usu, usu_pesq);
           else if( ch_usucad5.isSelected())
               usu.carregaTabela(2, tab_usu, usu_pesq);
           else if( ch_usuNcad5.isSelected())
                usu.carregaTabela(3, tab_usu, usu_pesq);
           else
               usu.carregaTabela(1, tab_usu, usu_pesq);
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_usucad5MouseClicked

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
 telas.alterartelaUsuario(lbl_login, lbl_senha, lbl_status, ch_login, ch_senha, ch_status, cad_usu, alterar, cancelar);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
          if(ch_login.isSelected()){//começo nome
            if(campo.CampoTexto(usu_login, loginerro)){
                usuario.setUsuario_login(usu_login.getText());
                usu.alterarUsuario(usuario,1);
            }}//fim nome
            if(ch_senha.isSelected()){//inicio email
                if(campo.Camposenha(usu_senha, conf_senha, senhaerro)){
                  usuario.setUsuario_senha(usu_senha.getText());
                  usu.alterarUsuario(usuario, 2);
                }
            }
            if(ch_status.isSelected()){
                usuario.setUsuario_status(usu_status.getSelectedIndex());
                usu.alterarUsuario(usuario, 3);
            }
                  usu.carregaTabela(1, tab_usu, usu_pesq);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Ususario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Ususario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Ususario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Ususario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Ususario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JPanel at_usuario5;
    private javax.swing.JButton btn_animais;
    private javax.swing.JButton btn_animais1;
    private javax.swing.JButton btn_calendario;
    private javax.swing.JButton btn_celeiro;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_rh;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JButton btn_usuario1;
    private javax.swing.JButton cad_usu;
    private javax.swing.JButton cancelar;
    private javax.swing.JCheckBox ch_login;
    private javax.swing.JCheckBox ch_senha;
    private javax.swing.JCheckBox ch_status;
    private javax.swing.JCheckBox ch_usuNcad5;
    private javax.swing.JCheckBox ch_usucad5;
    private javax.swing.JTextField conf_senha;
    private javax.swing.JLabel confsenhaerro;
    private javax.swing.JTabbedPane home;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JLabel jdata;
    private javax.swing.JTextField jnome;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel loginerro;
    private javax.swing.JLabel senhaerro;
    private javax.swing.JTable tab_usu;
    private javax.swing.JTextField usu_login;
    private javax.swing.JTextField usu_nome;
    private javax.swing.JTextField usu_pesq;
    private javax.swing.JTextField usu_senha;
    private javax.swing.JComboBox<String> usu_status;
    // End of variables declaration//GEN-END:variables
}
