/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

   

import controller.CalendarioDAO;
import model.Calendario;

/**
 *
 * @author maikon.rosa
 */
public class JF_Calendario extends javax.swing.JFrame {
 Calendario calendario = new Calendario();
 CalendarioDAO calendarioDao = new CalendarioDAO();
String nome = "sistema";   
 /**
     * Creates new form JF_Calendario
     */
    public JF_Calendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jcalendario = new javax.swing.JPanel();
        jcalendario_calendario = new com.toedter.calendar.JCalendar();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txt_anotacao_calendario = new javax.swing.JTextArea();
        btn_cadastrar_calendario = new javax.swing.JButton();
        btn_alterar_calendario = new javax.swing.JButton();
        btn_excluir_calendario = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        txt_calendario_id = new javax.swing.JTextField();
        sem_nota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcalendario_calendario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jcalendario_calendarioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jcalendario_calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcalendario_calendarioMouseClicked(evt);
            }
        });
        jcalendario_calendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcalendario_calendarioPropertyChange(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Anotações");

        txt_anotacao_calendario.setColumns(20);
        txt_anotacao_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_anotacao_calendario.setRows(5);
        jScrollPane10.setViewportView(txt_anotacao_calendario);

        btn_cadastrar_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cadastrar_calendario.setText("Cadastrar");
        btn_cadastrar_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_calendarioActionPerformed(evt);
            }
        });

        btn_alterar_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_alterar_calendario.setText("Alterar");
        btn_alterar_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_calendarioActionPerformed(evt);
            }
        });

        btn_excluir_calendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_excluir_calendario.setText("Excluir");
        btn_excluir_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_calendarioActionPerformed(evt);
            }
        });

        jLabel94.setText("ID:");

        txt_calendario_id.setEditable(false);

        sem_nota.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout JcalendarioLayout = new javax.swing.GroupLayout(Jcalendario);
        Jcalendario.setLayout(JcalendarioLayout);
        JcalendarioLayout.setHorizontalGroup(
            JcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JcalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcalendario_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(JcalendarioLayout.createSequentialGroup()
                        .addGroup(JcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addGroup(JcalendarioLayout.createSequentialGroup()
                                .addComponent(jLabel94)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_calendario_id, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sem_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JcalendarioLayout.createSequentialGroup()
                                .addComponent(btn_cadastrar_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir_calendario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_alterar_calendario)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JcalendarioLayout.setVerticalGroup(
            JcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JcalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcalendario_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JcalendarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel94)
                    .addComponent(txt_calendario_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sem_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JcalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar_calendario)
                    .addComponent(btn_excluir_calendario)
                    .addComponent(btn_alterar_calendario))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jcalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jcalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcalendario_calendarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jcalendario_calendarioAncestorAdded

    }//GEN-LAST:event_jcalendario_calendarioAncestorAdded

    private void jcalendario_calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcalendario_calendarioMouseClicked

    }//GEN-LAST:event_jcalendario_calendarioMouseClicked

    private void jcalendario_calendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcalendario_calendarioPropertyChange
        java.sql.Date sqldate_calendario = new java.sql.Date(jcalendario_calendario.getDate().getTime());
        calendario.setCalendario_data(sqldate_calendario);

        calendarioDao.consultarCalendarioDATA(sqldate_calendario, txt_calendario_id, txt_anotacao_calendario, btn_excluir_calendario, btn_alterar_calendario, btn_cadastrar_calendario, this);
    }//GEN-LAST:event_jcalendario_calendarioPropertyChange

    private void btn_cadastrar_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_calendarioActionPerformed


        java.sql.Date sqldate_calendario = new java.sql.Date(jcalendario_calendario.getDate().getTime());
        calendario.setCalendario_data(sqldate_calendario);
        calendario.setCalendario_desc(txt_anotacao_calendario.getText());
        if (!"".equals(txt_anotacao_calendario.getText())) {
            calendarioDao.salvarCalendario(calendario, nome, this);
            sem_nota.setText("");
        } else {
            sem_nota.setText("Adicione uma nota");
        }
    }//GEN-LAST:event_btn_cadastrar_calendarioActionPerformed

    private void btn_alterar_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_calendarioActionPerformed

        String how = txt_calendario_id.getText();
        calendario.setCalendario_id(Integer.valueOf(txt_calendario_id.getText()));
        java.sql.Date sqldate_calendario = new java.sql.Date(jcalendario_calendario.getDate().getTime());
        calendario.setCalendario_data(sqldate_calendario);
        calendario.setCalendario_desc(txt_anotacao_calendario.getText());
        if (!"".equals(txt_anotacao_calendario.getText())) {
            calendarioDao.alterarCalendario(calendario, nome, how, this);
        } else {
            sem_nota.setText("Se pretende deixar o campo vazio, sugiro que apague a nota");
        }
    }//GEN-LAST:event_btn_alterar_calendarioActionPerformed

    private void btn_excluir_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_calendarioActionPerformed
        
        String how = txt_calendario_id.getText();
        calendario.setCalendario_id(Integer.valueOf(txt_calendario_id.getText()));

        txt_calendario_id.setText("");
        txt_anotacao_calendario.setText("");
        calendarioDao.apagarCalendario(calendario, nome, how, this);
        sem_nota.setText("");
    }//GEN-LAST:event_btn_excluir_calendarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jcalendario;
    private javax.swing.JButton btn_alterar_calendario;
    private javax.swing.JButton btn_cadastrar_calendario;
    private javax.swing.JButton btn_excluir_calendario;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JScrollPane jScrollPane10;
    private com.toedter.calendar.JCalendar jcalendario_calendario;
    private javax.swing.JLabel sem_nota;
    private javax.swing.JTextArea txt_anotacao_calendario;
    private javax.swing.JTextField txt_calendario_id;
    // End of variables declaration//GEN-END:variables
}
